version: "3.7"
services:
  user-ms:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo_db:app_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "27017:27017"